#spring.application.name=Rewards Management API
#


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/rewards?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false




server:
  port: 9000

